name: ci

on:
  push:
  pull_request:

jobs:
  moonbit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonbitlang/setup-moonbit@v1
      - name: Check
        run: moon check
      - name: Test
        run: moon test
      - name: Build demo
        run: moon build
